name: Generate requirements.txt

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  generate_requirements:
    name: Test
    runs-on: ubuntu-latest
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: he0119/setup-python@main
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          curl https://raw.githubusercontent.com/HibiKier/zhenxun_bot/main/pyproject.toml -o pyproject.toml
          poetry update && poetry install
      - name: Generate Requirements
        run: poetry export --output requirements.txt --without-hashes
      - name: commit file
        run: |
          git config --local user.email "l1040186796@gmail.com"
          git config --local user.name "AkashiCoin"
          git add requirements.txt
          git commit -m "generate requirements.txt from github action" -a
      # push 
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}