name: Generate requirements.txt

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  generate_requirements:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: he0119/setup-python@main
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          curl https://raw.githubusercontent.com/HibiKier/zhenxun_bot/main/pyproject.toml -o pyproject.toml
          curl https://raw.githubusercontent.com/HibiKier/zhenxun_bot/main/poetry.lock -o poetry.lock
      - name: Generate Requirements
        run: |
          poetry export --output requirements.txt --without-hashes
          rm -f pyproject.toml poetry.lock
      # push 
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'master'